In [1]:
import torch 
x = torch.arange(10).float()
x.unsqueeze_(1)
y = x ** 3 / 1000

In [18]:
from src.ptf.trainer import _BaseTrainer
from src.ptf.model import _BaseModel
import torch.nn as nn
from torch.utils.data import TensorDataset
from torch.optim import SGD

class Recon(_BaseModel):
    def compute_loss(self, network, batch):
        x, y = batch
        out = network(x)
        return nn.MSELoss()(out, y)

dataset = TensorDataset(x, y)
network = nn.Sequential(
    nn.Linear(1, 8),
    nn.ReLU(),
    nn.Linear(8, 8),
    nn.ReLU(),
    nn.Linear(8, 1)
)
model = Recon()
optimizer = SGD(network.parameters(), lr = 0.1)

trainer = _BaseTrainer(
    hparams=dict(
        epoch_num = 30,
        batch_size = 3,
        gradient_accumulate=2
    ),
    modules=dict(
        dataset=dataset,
        network=network,
        model=model,
        optimizer=optimizer
    )
)

In [22]:
trainer.loop()

tensor([-0.1687, -0.0511,  0.0197,  0.2874, -0.4383, -0.3429,  0.4261, -0.7566])
tensor([0.0000, 0.0000, 0.0000, 0.9843, 0.0000, 0.0000, 0.2702, 0.0000])

tensor([-0.1687, -0.0511,  0.0197,  0.2874, -0.4383, -0.3429,  0.4261, -0.7566])
tensor([0.0000, 0.0000, 0.0000, 2.3213, 0.0000, 0.0000, 0.6352, 0.0000])

tensor([-0.1687, -0.0511,  0.0197,  0.0553, -0.4383, -0.3429,  0.3626, -0.7566])
tensor([0.0000, 0.0000, 0.0000, 0.8785, 0.0000, 0.0000, 1.8788, 0.0000])

tensor([-0.1687, -0.0511,  0.0197,  0.0553, -0.4383, -0.3429,  0.3626, -0.7566])
tensor([0.0000, 0.0000, 0.0000, 1.7137, 0.0000, 0.0000, 4.1574, 0.0000])

tensor([-0.1687, -0.0511,  0.0197, -0.1161, -0.4383, -0.3429, -0.0532, -0.7566])
tensor([0.0000, 0.0000, 0.0000, 0.0041, 0.0000, 0.0000, 0.2367, 0.0000])

tensor([-0.1687, -0.0511,  0.0197, -0.1161, -0.4383, -0.3429, -0.0532, -0.7566])
tensor([0.0000, 0.0000, 0.0000, 0.0041, 0.0000, 0.0000, 0.4479, 0.0000])

tensor([-0.1687, -0.0511,  0.0197, -0.1165, -0.4383, -0.3429, -0.0979,

In [23]:
((network(x) - y) ** 2).sum()

tensor(0.3604, grad_fn=<SumBackward0>)